# === WRITE MODEL (PostgreSQL) ===
spring.datasource.write.jdbc-url=jdbc:postgresql://localhost:5432/eventmaster_db
spring.datasource.write.username=eventmaster
spring.datasource.write.password=password
spring.datasource.write.driver-class-name=org.postgresql.Driver

# === READ MODEL (CockroachDB) ===
spring.datasource.read.jdbc-url=jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable
spring.datasource.read.username=root
spring.datasource.read.password=
spring.datasource.read.driver-class-name=org.postgresql.Driver

# === Konfiguracja JPA (globalna) ===
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# === Konfiguracja Flyway ===
spring.flyway.url=${spring.datasource.write.jdbc-url}
spring.flyway.user=${spring.datasource.write.username}
spring.flyway.password=${spring.datasource.write.password}
spring.flyway.locations=classpath:db/migration

server.port=8080
management.endpoint.health.show-details=always

# --- Konfiguracja Konsumenta Kafki ---
spring.kafka.consumer.group-id=eventmaster-command-handlers
spring.kafka.consumer.auto-offset-reset=earliest
# Użyjemy JSON Deserializera
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Kluczowe: musimy powiedzieć deserializerowi, jakich klas oczekuje
spring.kafka.consumer.properties.spring.json.trusted.packages=com.eventmaster.backend.events.command
spring.kafka.consumer.properties.spring.json.value.default.type=com.eventmaster.backend.events.command.CreateEventCommand
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/eventmaster

# --- Kafka ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
